version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: terraform
    directory: /deployment
    schedule:
      interval: weekly
      day: monday
    groups:
      terraform-providers:
        patterns:
          - '*'
