"""Registry of resource-check quota keys used by reporting metric selection."""
from importlib import import_module


_CHECK_MODULES = (
    ('modules.qmchecks.ec2.ec2', 'ec2'),
    ('modules.qmchecks.appstream', 'appstream2'),
    ('modules.qmchecks.vpc.vpc', 'vpc'),
    ('modules.qmchecks.lambda_checks.lambda_checks', 'lambda'),
    ('modules.qmchecks.account_services', None),
    ('modules.qmchecks.elb', 'elasticloadbalancing'),
    ('modules.qmchecks.stepfunctions', 'states'),
    ('modules.qmchecks.ecr', 'ecr'),
    ('modules.qmchecks.autoscaling', 'autoscaling'),
    ('modules.qmchecks.apigateway', 'apigateway'),
    ('modules.qmchecks.ecs', 'ecs'),
    ('modules.qmchecks.firehose', 'firehose'),
    ('modules.qmchecks.eventbridge', 'events'),
    ('modules.qmchecks.cloudtrail', 'cloudtrail'),
    ('modules.qmchecks.sns', 'sns'),
    ('modules.qmchecks.secretsmanager', 'secretsmanager'),
    ('modules.qmchecks.access_analyzer', 'access-analyzer'),
    ('modules.qmchecks.guardduty', 'guardduty'),
    ('modules.qmchecks.securityhub', 'securityhub'),
    ('modules.qmchecks.transfer', 'transfer'),
    ('modules.qmchecks.macie', 'macie2'),
    ('modules.qmchecks.inspector', 'inspector2'),
    ('modules.qmchecks.efs', 'elasticfilesystem'),
    ('modules.qmchecks.fsx', 'fsx'),
    ('modules.qmchecks.lakeformation', 'lakeformation'),
    ('modules.qmchecks.xray', 'xray'),
    ('modules.qmchecks.appmesh', 'appmesh'),
    ('modules.qmchecks.redshift', 'redshift'),
    ('modules.qmchecks.timestream', 'timestream'),
    ('modules.qmchecks.rds_resources', 'rds'),
    ('modules.qmchecks.transcribe', 'transcribe'),
    ('modules.qmchecks.polly', 'polly'),
    ('modules.qmchecks.lex', 'lex'),
    ('modules.qmchecks.network_firewall', 'network-firewall'),
    ('modules.qmchecks.networkinsights', 'networkinsights'),
    ('modules.qmchecks.ses', 'ses'),
    ('modules.qmchecks.connect', 'connect'),
    ('modules.qmchecks.cleanrooms_ml', 'cleanrooms-ml'),
    ('modules.qmchecks.auditmanager', 'auditmanager'),
    ('modules.qmchecks.resiliencehub', 'resiliencehub'),
    ('modules.qmchecks.storagegateway', 'storagegateway'),
    ('modules.qmchecks.omics', 'omics'),
    ('modules.qmchecks.iotfleetwise', 'iotfleetwise'),
    ('modules.qmchecks.forecast', 'forecast'),
    ('modules.qmchecks.pinpoint', 'pinpoint'),
    ('modules.qmchecks.deadline', 'deadline'),
    ('modules.qmchecks.appconfig', 'appconfig'),
    ('modules.qmchecks.scheduler', 'scheduler'),
    ('modules.qmchecks.resource_groups', 'resource-groups'),
    ('modules.qmchecks.cloudformation', 'cloudformation'),
    ('modules.qmchecks.cloudwatchpredictions', 'cloudwatchpredictions'),
    ('modules.qmchecks.application_autoscaling', 'application-autoscaling'),
    ('modules.qmchecks.kms', 'kms'),
    ('modules.qmchecks.ssm', 'ssm'),
    ('modules.qmchecks.route53resolver', 'route53resolver'),
    ('modules.qmchecks.mq', 'mq'),
    ('modules.qmchecks.directoryservice', 'ds'),
    ('modules.qmchecks.opensearch', 'opensearch'),
    ('modules.qmchecks.elasticbeanstalk', 'elasticbeanstalk'),
    ('modules.qmchecks.batch', 'batch'),
    ('modules.qmchecks.s3', 's3'),
    ('modules.qmchecks.codeguruprofiler', 'codeguru-profiler'),
    ('modules.qmchecks.memorydb', 'memorydb'),
    ('modules.qmchecks.personalize', 'personalize'),
    ('modules.qmchecks.sagemaker_resources', 'sagemaker'),
    ('modules.qmchecks.mediaconvert', 'mediaconvert'),
    ('modules.qmchecks.ivs', 'ivs'),
    ('modules.qmchecks.workspaces_web', 'workspaces-web'),
    ('modules.qmchecks.specialized', None),
    ('modules.qmchecks.streaming', None),
    ('modules.qmchecks.media_extra', None),
    ('modules.qmchecks.management_counts', None),
    ('modules.qmchecks.misc_counts', None),
    ('modules.qmchecks.rest_counts', None),
    ('modules.qmchecks.servicecatalog', 'servicecatalog'),
    ('modules.qmchecks.wafv2', 'wafv2'),
    ('modules.qmchecks.waf_regional', 'waf-regional'),
    ('modules.qmchecks.acm', 'acm'),
    ('modules.qmchecks.cognito', 'cognito-idp'),
    ('modules.qmchecks.backup', 'backup'),
    ('modules.qmchecks.glue', 'glue'),
    ('modules.qmchecks.emr', 'elasticmapreduce'),
    ('modules.qmchecks.datasync', 'datasync'),
    ('modules.qmchecks.codebuild', 'codebuild'),
    ('modules.qmchecks.codepipeline', 'codepipeline'),
    ('modules.qmchecks.codeartifact', 'codeartifact'),
    ('modules.qmchecks.logs', 'logs'),
    ('modules.qmchecks.dynamodb', 'dynamodb'),
    ('modules.qmchecks.elasticache', 'elasticache'),
    ('modules.qmchecks.docdb', 'docdb'),
    ('modules.qmchecks.neptune', 'neptune'),
    ('modules.qmchecks.bedrock', 'bedrock'),
    ('modules.qmchecks.bedrock_agentcore', 'bedrock-agentcore'),
    ('modules.qmchecks.rekognition', 'rekognition'),
    ('modules.qmchecks.comprehend', 'comprehend'),
    ('modules.qmchecks.textract', 'textract'),
    ('modules.qmchecks.directconnect', 'directconnect'),
    ('modules.qmchecks.iot', 'iot'),
    ('modules.qmchecks.iotcore', 'iotcore'),
    ('modules.qmchecks.iotcore', 'iotcore'),
    ('modules.qmchecks.appsync', 'appsync'),
    ('modules.qmchecks.config_service', 'config'),
    ('modules.qmchecks.dms_resources', 'dms'),
    ('modules.qmchecks.mgn', 'mgn'),
    ('modules.qmchecks.groundstation', 'groundstation'),
    ('modules.qmchecks.sitewise', 'iotsitewise'),
    ('modules.qmchecks.twinmaker', 'iottwinmaker'),
    ('modules.qmchecks.robomaker', 'robomaker'),
    ('modules.qmchecks.workspaces', 'workspaces'),
    ('modules.qmchecks.finspace', 'finspace'),
    ('modules.qmchecks.m2', 'm2'),
    ('modules.qmchecks.entityresolution', 'entityresolution'),
    ('modules.qmchecks.datazone', 'datazone'),
    ('modules.qmchecks.apprunner', 'apprunner'),
    ('modules.qmchecks.amplify', 'amplify'),
    ('modules.qmchecks.cases', 'cases'),
    ('modules.qmchecks.airflow', 'airflow'),
    ('modules.qmchecks.amplifyuibuilder', 'amplifyuibuilder'),
    ('modules.qmchecks.evs', 'evs'),
    ('modules.qmchecks.lightsail', 'lightsail'),
    ('modules.qmchecks.mediastore', 'mediastore'),
    ('modules.qmchecks.mediatailor', 'mediatailor'),
    ('modules.qmchecks.kinesisvideo', 'kinesisvideo'),
    ('modules.qmchecks.kinesis_resources', 'kinesis'),
    ('modules.qmchecks.kinesisanalytics', 'kinesisanalytics'),
    ('modules.qmchecks.eks', 'eks'),
    ('modules.qmchecks.codedeploy', 'codedeploy'),
    ('modules.qmchecks.cassandra', 'cassandra'),
    ('modules.qmchecks.qldb', 'qldb'),
    ('modules.qmchecks.cloud9', 'cloud9'),
    ('modules.qmchecks.resource_explorer', 'resource-explorer-2'),
    ('modules.qmchecks.neptune_graph', 'neptune-graph'),
    ('modules.qmchecks.location', 'geo'),
    ('modules.qmchecks.appintegrations', 'app-integrations'),
    ('modules.qmchecks.iotevents', 'iotevents'),
    ('modules.qmchecks.iotanalytics', 'iotanalytics'),
    ('modules.qmchecks.pcs', 'pcs'),
    ('modules.qmchecks.grafana', 'grafana'),
    ('modules.qmchecks.oam', 'oam'),
    ('modules.qmchecks.networkmonitor', 'networkmonitor'),
    ('modules.qmchecks.gameliftstreams', 'gameliftstreams'),
    ('modules.qmchecks.gamelift', 'gamelift'),
    ('modules.qmchecks.dsql', 'dsql'),
    ('modules.qmchecks.payment_cryptography', 'payment-cryptography'),
    ('modules.qmchecks.serverlessrepo', 'serverlessrepo'),
    ('modules.qmchecks.swf', 'swf'),
    ('modules.qmchecks.cloudhsm', 'cloudhsm'),
    ('modules.qmchecks.kafka', 'kafka'),
    ('modules.qmchecks.proton', 'proton'),
    ('modules.qmchecks.imagebuilder', 'imagebuilder'),
    ('modules.qmchecks.fms', 'fms'),
    ('modules.qmchecks.kafkaconnect', 'kafkaconnect'),
    ('modules.qmchecks.license_manager', 'license-manager'),
    ('modules.qmchecks.rolesanywhere', 'rolesanywhere'),
    ('modules.qmchecks.internetmonitor', 'internetmonitor'),
    ('modules.qmchecks.route53profiles', 'route53profiles'),
    ('modules.qmchecks.docdb_elastic', 'docdb-elastic'),
    ('modules.qmchecks.databrew', 'databrew'),
    ('modules.qmchecks.cognito_identity', 'cognito-identity'),
    ('modules.qmchecks.wellarchitected', 'wellarchitected'),
    ('modules.qmchecks.ssm_contacts', 'ssm-contacts'),
    ('modules.qmchecks.dataexchange', 'dataexchange'),
    ('modules.qmchecks.rbin', 'rbin'),
    ('modules.qmchecks.discovery', 'discovery'),
    ('modules.qmchecks.ssm_incidents', 'ssm-incidents'),
    ('modules.qmchecks.workspaces_instances', 'workspaces-instances'),
    ('modules.qmchecks.repostspace', 'repostspace'),
    ('modules.qmchecks.evidently', 'evidently'),
    ('modules.qmchecks.applicationsignals', 'application-signals'),
    ('modules.qmchecks.ram', 'ram'),
    ('modules.qmchecks.fis', 'fis'),
    ('modules.qmchecks.aoss', 'aoss'),
    # Composite collector for services whose checks are scoped by quota code.
    ('modules.qmchecks.new_services', None),
)


def custom_keys():
    keys = set()
    for module_name, service in _CHECK_MODULES:
        module = import_module(module_name)
        keys.update(getattr(module, 'CUSTOM_KEYS', ()))
        # Some collectors keep a small backwards-compatible CHECKS export
        # while exposing their complete catalog-backed set as ALL_CHECKS.
        checks = getattr(module, 'ALL_CHECKS', getattr(module, 'CHECKS', ()))
        if isinstance(checks, dict):
            for check_service, entries in checks.items():
                keys.update((check_service, code) for code, _name, _check in entries)
        else:
            for code, _name, _check in checks:
                # Account-services checks are selected by their own quota service.
                keys.add((service, code)) if service else None
    return keys
